In [1]:
import neuralnet as n
from sklearn.preprocessing import LabelEncoder
from neuralnet import *

In [2]:
import pandas as pd

def get_data(path):
    data = pd.read_csv(path, index_col=0)
    cols = list(data.columns)
    target = cols.pop()
    X = data[cols].copy()
    y = data[target].copy()
    y = LabelEncoder().fit_transform(y)
    return np.array(X), np.array(y)

In [179]:
X, y = get_data("iris.csv")

In [141]:
X = np.array([[1, 1]])
y = np.array([1])

In [213]:
import importlib
importlib.reload(n)
from neuralnet import *

In [231]:
nn = NeuralNet()
nn.addLayer(DenseLayer(10, 'softmax'))
nn.addLayer(DenseLayer(3, "softmax"))
nn.setLossFunc('crossentropy')

nn.initParams(X[0].shape[0])
nn.learningRate = 0.01

In [236]:
for i in range(1):

    ypred = nn.forward(X.T)
    nn.backprop(ypred.T, y)

    if i % 1 == 0:
        print(f'inter={i} accuracy={nn._get_accuracy(ypred.T, y)} cost={nn.rms_cost(ypred.T, y)}')

inter=0 accuracy=0.0 cost=375.00238321410694
inter=1 accuracy=0.0 cost=375.0023840141012
inter=2 accuracy=0.0 cost=375.0023848195191
inter=3 accuracy=0.0 cost=375.0023856303948
inter=4 accuracy=0.0 cost=375.00238644676244
inter=5 accuracy=0.0 cost=375.0023872686562
inter=6 accuracy=0.0 cost=375.00238809611017
inter=7 accuracy=0.0 cost=375.00238892915866
inter=8 accuracy=0.0 cost=375.0023897678357
inter=9 accuracy=0.0 cost=375.00239061217565
inter=10 accuracy=0.0 cost=375.00239146221253
inter=11 accuracy=0.0 cost=375.00239231798076
inter=12 accuracy=0.0 cost=375.00239317951446
inter=13 accuracy=0.0 cost=375.00239404684777
inter=14 accuracy=0.0 cost=375.0023949200149
inter=15 accuracy=0.0 cost=nan
inter=16 accuracy=0.3333333333333333 cost=nan
inter=17 accuracy=0.3333333333333333 cost=nan
inter=18 accuracy=0.3333333333333333 cost=nan
inter=19 accuracy=0.3333333333333333 cost=nan
inter=20 accuracy=0.3333333333333333 cost=nan
inter=21 accuracy=0.3333333333333333 cost=nan
inter=22 accuracy=0

c:\Users\ANEETHALAN\Documents\Projects\NeuralNet\neuralnet.py:16: RuntimeWarning: overflow encountered in exp
  exp_scores = np.exp(X)
c:\Users\ANEETHALAN\Documents\Projects\NeuralNet\neuralnet.py:17: RuntimeWarning: invalid value encountered in divide
  probs = exp_scores / np.sum(exp_scores, axis=0, keepdims=True)


In [235]:
nn.biases[0]

array([[-1.64152332],
       [-0.18205987],
       [ 0.05295285],
       [-0.03810925],
       [ 2.94333783],
       [ 0.32401004],
       [-0.05356858],
       [-8.59052117],
       [-0.08554289],
       [ 0.02021879]])

In [224]:
nn.weights[0]

array([[ 0.15246656, -0.67127945, -0.91033747],
       [ 0.57520678,  0.69431285,  0.585202  ],
       [ 0.56092809, -0.53683816,  0.48261479],
       [-0.0649677 , -0.19971788, -0.613549  ],
       [ 0.68328717, -0.62839407, -0.34153512],
       [ 0.436011  , -0.26588093,  0.20896691],
       [ 0.48193337, -0.40876402,  0.28461851],
       [ 0.6309858 ,  0.52298112,  0.43324197],
       [-0.58168223, -0.47702866, -0.13767932],
       [ 0.95753848, -0.53055094,  0.16461139]])

In [206]:
pd.DataFrame(ypred)

0              1              2              3              4    \
0  -6.666667e-03  -6.666667e-03  -6.666667e-03  -6.666667e-03  -6.666667e-03   
1  2.149142e-214  1.965981e-193  3.390672e-198  3.020539e-201  1.380391e-218   
2   6.666667e-03   6.666667e-03   6.666667e-03   6.666667e-03   6.666667e-03   

             5              6              7              8              9    \
0  -6.666667e-03  -6.666667e-03  -6.666667e-03  -6.666667e-03  -6.666667e-03   
1  5.278536e-245  1.086491e-211  8.003793e-214  3.060851e-189  9.302214e-200   
2   6.666667e-03   6.666667e-03   6.666667e-03   6.666667e-03   6.666667e-03   

   ...  140  141  142  143  144  145  146  147  148  149  
0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  

[3 rows x 150 columns]

In [150]:
ypred

array([[0.95635729]])

In [152]:
X[0]

array([3.5, 1.4, 0.2])

In [153]:
X

array([[3.5, 1.4, 0.2],
       [3. , 1.4, 0.2],
       [3.2, 1.3, 0.2],
       [3.1, 1.5, 0.2],
       [3.6, 1.4, 0.2],
       [3.9, 1.7, 0.4],
       [3.4, 1.4, 0.3],
       [3.4, 1.5, 0.2],
       [2.9, 1.4, 0.2],
       [3.1, 1.5, 0.1],
       [3.7, 1.5, 0.2],
       [3.4, 1.6, 0.2],
       [3. , 1.4, 0.1],
       [3. , 1.1, 0.1],
       [4. , 1.2, 0.2],
       [4.4, 1.5, 0.4],
       [3.9, 1.3, 0.4],
       [3.5, 1.4, 0.3],
       [3.8, 1.7, 0.3],
       [3.8, 1.5, 0.3],
       [3.4, 1.7, 0.2],
       [3.7, 1.5, 0.4],
       [3.6, 1. , 0.2],
       [3.3, 1.7, 0.5],
       [3.4, 1.9, 0.2],
       [3. , 1.6, 0.2],
       [3.4, 1.6, 0.4],
       [3.5, 1.5, 0.2],
       [3.4, 1.4, 0.2],
       [3.2, 1.6, 0.2],
       [3.1, 1.6, 0.2],
       [3.4, 1.5, 0.4],
       [4.1, 1.5, 0.1],
       [4.2, 1.4, 0.2],
       [3.1, 1.5, 0.2],
       [3.2, 1.2, 0.2],
       [3.5, 1.3, 0.2],
       [3.6, 1.4, 0.1],
       [3. , 1.3, 0.2],
       [3.4, 1.5, 0.2],
       [3.5, 1.3, 0.3],
       [2.3, 1.3