In [1]:
import neuralnet as n
from sklearn.preprocessing import LabelEncoder
from neuralnet import *

In [145]:
import pandas as pd

def get_data(path):
    data = pd.read_csv(path, index_col=0).sample(frac = 1)
    cols = list(data.columns)
    target = cols.pop()
    X = data[cols].copy()
    y = data[target].copy()

    y = np.array(LabelEncoder().fit_transform(y))
    
    onehot_y = np.zeros((y.size, y.max() + 1))
    onehot_y[np.arange(y.size), y] = 1

    return np.array(X), onehot_y

In [146]:
X, y = get_data("iris.csv")

In [115]:
# X = np.array([[1, 1, 1],[0,0,0], [1,1,0]])
# y = np.array([[0, 1],
#               [1,0],
#               [1,0]])

In [178]:
import importlib
importlib.reload(n)
from neuralnet import *

In [179]:
nn = NeuralNet()
nn.addLayer(DenseLayer(6, 'relu'))
nn.addLayer(DenseLayer(10, 'sigmoid'))
nn.addLayer(DenseLayer(3, "sigmoid"))
nn.setLossFunc('rms')

nn.initParams(3)
nn.learningRate = 0.01

In [180]:
for i in range(10000):

    ypred = nn.forward(X.T)
    nn.backprop(ypred.T, y)

    if i % 1 == 0:
        print(f'inter={i} accuracy={nn._get_accuracy(np.rint(ypred.T), y)} cost={nn.rms_cost(ypred.T, y)}')

inter=0 accuracy=0.0 cost=68.11053859725382
inter=1 accuracy=30.0 cost=58.946250868735675
inter=2 accuracy=33.333333333333336 cost=53.68542761641307
inter=3 accuracy=0.0 cost=51.27053729688505
inter=4 accuracy=0.0 cost=50.24424210395113
inter=5 accuracy=0.0 cost=49.751112036489076
inter=6 accuracy=0.0 cost=49.44485377395391
inter=7 accuracy=0.0 cost=49.19551470889079
inter=8 accuracy=0.0 cost=48.954094908001245
inter=9 accuracy=0.0 cost=48.696964211709805
inter=10 accuracy=0.0 cost=48.41507392072445
inter=11 accuracy=0.0 cost=48.10208869379912
inter=12 accuracy=0.0 cost=47.74763931085714
inter=13 accuracy=0.0 cost=47.33920941179238
inter=14 accuracy=0.0 cost=46.86067328576537
inter=15 accuracy=0.0 cost=46.291929326945436
inter=16 accuracy=0.0 cost=45.60837426995045
inter=17 accuracy=0.0 cost=44.7919399239481
inter=18 accuracy=0.0 cost=43.895428430342335
inter=19 accuracy=0.0 cost=43.041228613183705
inter=20 accuracy=0.0 cost=42.22804322355801
inter=21 accuracy=0.0 cost=41.4301936270023

In [170]:
np.rint(ypred.T)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0

In [171]:
y

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0

In [28]:
nn.weights[0]

array([[ 0.28105517,  0.07692743, -0.78864198],
       [ 0.71867424,  0.54931942,  0.00818223],
       [-0.18941526,  0.70384765, -0.4603908 ],
       [ 0.61624405, -0.48668643, -0.59826418],
       [ 0.16414343, -0.41947057, -0.99942359],
       [ 0.72285856,  0.65593075, -0.17123935],
       [ 0.11221229,  0.36590835,  0.43815636],
       [-0.37352494, -0.0751255 ,  0.09300161],
       [ 0.20597903, -0.8794374 ,  0.60559054],
       [ 0.63731778,  0.52042011,  0.32628197]])

In [70]:
nn._get_accuracy(y, ypred.T)

0.0

In [152]:
y

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0

In [153]:
ypred.T

array([[9.99095191e-01, 1.02569228e-03, 8.90331172e-08],
       [2.12902173e-03, 9.90315943e-01, 8.09546773e-03],
       [5.61250903e-06, 1.83671360e-03, 9.98980567e-01],
       [3.46301746e-03, 7.68807307e-01, 2.23267877e-01],
       [9.99740393e-01, 2.70288470e-04, 2.78971274e-08],
       [1.84491970e-08, 1.85170863e-05, 9.99993901e-01],
       [9.67191172e-01, 4.78515189e-02, 2.46661116e-06],
       [9.99963024e-01, 3.23552980e-05, 3.94145367e-09],
       [9.99294937e-01, 6.95144662e-04, 2.84621928e-08],
       [5.61016005e-06, 1.42874365e-03, 9.99255671e-01],
       [9.99794403e-01, 2.07825475e-04, 2.13922191e-08],
       [7.92286694e-05, 1.40182897e-02, 9.90030256e-01],
       [9.99537883e-01, 4.69573944e-04, 3.79721577e-08],
       [9.99969470e-01, 2.72821447e-05, 4.19087899e-09],
       [9.99941870e-01, 5.02429852e-05, 4.57231355e-09],
       [9.99980895e-01, 1.54816105e-05, 1.50607272e-09],
       [3.90167082e-04, 4.01533078e-02, 9.73336937e-01],
       [9.99729332e-01, 2.96416

In [18]:
nn._get_accuracy(y, ypred)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [82]:
y

array([[0, 1],
       [1, 0]])

In [77]:
get

0

In [88]:
X

array([[1, 1, 1],
       [0, 0, 0]])

In [86]:
X

array([[3.5, 1.4, 0.2],
       [3. , 1.4, 0.2],
       [3.2, 1.3, 0.2],
       [3.1, 1.5, 0.2],
       [3.6, 1.4, 0.2],
       [3.9, 1.7, 0.4],
       [3.4, 1.4, 0.3],
       [3.4, 1.5, 0.2],
       [2.9, 1.4, 0.2],
       [3.1, 1.5, 0.1],
       [3.7, 1.5, 0.2],
       [3.4, 1.6, 0.2],
       [3. , 1.4, 0.1],
       [3. , 1.1, 0.1],
       [4. , 1.2, 0.2],
       [4.4, 1.5, 0.4],
       [3.9, 1.3, 0.4],
       [3.5, 1.4, 0.3],
       [3.8, 1.7, 0.3],
       [3.8, 1.5, 0.3],
       [3.4, 1.7, 0.2],
       [3.7, 1.5, 0.4],
       [3.6, 1. , 0.2],
       [3.3, 1.7, 0.5],
       [3.4, 1.9, 0.2],
       [3. , 1.6, 0.2],
       [3.4, 1.6, 0.4],
       [3.5, 1.5, 0.2],
       [3.4, 1.4, 0.2],
       [3.2, 1.6, 0.2],
       [3.1, 1.6, 0.2],
       [3.4, 1.5, 0.4],
       [4.1, 1.5, 0.1],
       [4.2, 1.4, 0.2],
       [3.1, 1.5, 0.2],
       [3.2, 1.2, 0.2],
       [3.5, 1.3, 0.2],
       [3.6, 1.4, 0.1],
       [3. , 1.3, 0.2],
       [3.4, 1.5, 0.2],
       [3.5, 1.3, 0.3],
       [2.3, 1.3

In [61]:
ypred.shape

(2, 1)